# Generated by Django 6.0.3 on 2026-04-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=200)),
                ('member_classification', models.CharField(blank=True, max_length=50)),
                ('member_role', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Justificada', 'Justificada')], default='Ausente', max_length=20)),
                ('arrival_time', models.CharField(blank=True, max_length=10)),
                ('observations', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_id', models.CharField(blank=True, max_length=100)),
                ('church_name', models.CharField(max_length=200)),
                ('pastor_name', models.CharField(blank=True, max_length=200)),
                ('church_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('commitment_type', models.CharField(choices=[('Reunião', 'Reuniao'), ('Visita', 'Visita'), ('Apresentação', 'Apresentacao'), ('Culto Parceiro', 'Culto Parceiro'), ('Ação Evangelística', 'Acao Evangelistica')], max_length=30)),
                ('responsible', models.CharField(blank=True, max_length=200)),
                ('observations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], default='Agendado', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meeting_type', models.CharField(choices=[('Administrativa', 'Administrativa'), ('Ordinária', 'Ordinaria'), ('Extraordinária', 'Extraordinaria'), ('Culto', 'Culto'), ('Oração', 'Oracao')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('leader', models.CharField(blank=True, max_length=200)),
                ('bible_reading', models.CharField(blank=True, max_length=200)),
                ('observations', models.TextField(blank=True)),
                ('allow_attendance', models.BooleanField(default=True)),
                ('agenda_items', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Agendada', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=20)),
                ('classification', models.CharField(choices=[('Gideão', 'Gideao'), ('Auxiliar', 'Auxiliar')], max_length=20)),
                ('bond', models.CharField(choices=[('Membro', 'Membro'), ('Oficial', 'Oficial')], max_length=20)),
                ('official_role', models.CharField(choices=[('Presidente', 'Presidente'), ('Vice-presidente', 'Vice Presidente'), ('Capelão', 'Capelao'), ('Secretário', 'Secretario'), ('Tesoureiro', 'Tesoureiro'), ('Nenhum', 'Nenhum')], default='Nenhum', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('field', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=100)),
                ('meeting_title', models.CharField(max_length=200)),
                ('opening_time', models.CharField(blank=True, max_length=10)),
                ('closing_time', models.CharField(blank=True, max_length=10)),
                ('full_text', models.TextField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('signers', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Aprovada', 'Aprovada'), ('Revisão', 'Revisao')], default='Rascunho', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerChurch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pastor_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('observations', models.TextField(blank=True)),
                ('partnership_status', models.CharField(choices=[('Ativa', 'Ativa'), ('Inativa', 'Inativa'), ('Pendente', 'Pendente')], default='Ativa', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
